name: Run Node Tests (composite)
description: Runs the repository's Node.js test suite with coverage and spec reporter

inputs: {}

runs:
  using: composite
  steps:
    - name: Check out code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup Node.js
      uses: ./setup-node

    - name: Run action tests with coverage
      shell: bash
      run: |
        set -euo pipefail
        echo "Running Node tests with coverage"
        node --version
        summary_path="$RUNNER_TEMP/node-test-output.txt"
        set +e
        npx --yes c8 \
          --check-coverage --per-file \
          --statements 90 --branches 75 --functions 80 --lines 90\
          -r text -r lcov \
          node --test --test-reporter=spec | tee "$summary_path"
        test_status=${PIPESTATUS[0]}
        set -e
        {
          echo "\n### Node test output";
          cat "$summary_path";
        } >> "$GITHUB_STEP_SUMMARY"
        exit $test_status
