name: 'Configure Nuget Source'
description: 'Configures NuGet to use a source'
inputs:
  name: 
    description: 'Name of the NuGet source'
    required: true
  password:
    description: 'Personal Access Token for authentication'
    required: true
  url:
    description: 'URL of the NuGet feed'
    required: true
  username:
    description: 'Username for source authentication'
    required: true
runs:
  using: "composite"
  steps:
    - name: Configure NuGet authentication
      shell: bash
      run: |
        dotnet nuget list source
        if dotnet nuget list source | grep -q '${{ inputs.url }}'; then
          echo "NuGet source '${{ inputs.name }}' already exists. Updating..."
          dotnet nuget update source '${{ inputs.name }}' --username '${{ inputs.username }}' --password ${{ inputs.password }} --store-password-in-clear-text
          exit 0
        fi
        echo "Adding NuGet source '${{ inputs.name }}'..."
        dotnet nuget add source --username '${{ inputs.username }}' --password ${{ inputs.password }} --store-password-in-clear-text --name '${{ inputs.name }}' '${{ inputs.url }}'