name: Demo - Get Match
description: Demo for get-match composite action

inputs:
  debug-mode:
    description: "Enable debug mode."
    required: false
    default: "false"

runs:
  using: composite
  steps:
    - name: Setup summary file
      shell: bash
      run: |
        echo "SUMMARY_FILE=$GITHUB_WORKSPACE/demo-get-match-summary.txt" >> $GITHUB_ENV
        : > $GITHUB_WORKSPACE/demo-get-match-summary.txt

    - name: Extract words
      id: words
      uses: ./get-match
      with:
        debug-mode: ${{ inputs.debug-mode }}
        string: "alpha beta gamma"
        regex: '(\\w+)'
        output-is-json: "true"

    - name: Assert words output
      uses: ./testing/assert
      with:
        expected: '["alpha","beta","gamma"]'
        mode: exact
        actual: ${{ steps.words.outputs.matches }}
        test-name: "words extraction"
        summary-file: ${{ env.SUMMARY_FILE }}

    - name: No matches scenario
      id: none
      uses: ./get-match
      with:
        string: "no digits here"
        regex: '(\\d+)'
        output-is-json: "true"

    - name: Assert no matches
      uses: ./testing/assert
      with:
        expected: "[]"
        mode: exact
        actual: ${{ steps.none.outputs.matches }}
        test-name: "no matches returns empty array"
        summary-file: ${{ env.SUMMARY_FILE }}

    - name: Summary
      shell: bash
      if: always()
      run: |
        echo "### Demo get-match" >> $GITHUB_STEP_SUMMARY
        echo "All Tests:" >> $GITHUB_STEP_SUMMARY
        cat "$SUMMARY_FILE" >> $GITHUB_STEP_SUMMARY
