name: Run Demo Workflows (composite)
description: Executes all demo composite actions used by demo-all workflow

inputs:
  github-token:
    description: "GitHub token with permissions to publish to GitHub Packages (NuGet)."
    required: false
    default: ""

runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Demo - github release
      uses: ./.github/actions/demo-github-release

    - name: Demo - get-unique-project-directories
      uses: ./.github/actions/demo-get-unique-project-directories

    - name: Demo - find
      uses: ./.github/actions/demo-find

    - name: Demo - nuget-release-validation
      uses: ./.github/actions/demo-validate-release
      with:
        ref-name: "release/Demo.Library/1.2.3"
        package: "Demo.Library"
        version: "1.2.3"

    - name: Demo - generate-https-cert
      uses: ./.github/actions/demo-generate-https-cert

    - name: Demo - code standards (fail)
      uses: ./.github/actions/demo-code-standards
      with:
        directory: "./src/demo/coding-standards-fail"

    - name: Demo - code standards (fail, roslyn version)
      uses: ./.github/actions/demo-code-standards
      with:
        directory: "./src/demo/coding-standards-fail"
        roslyn-version: "4.9.2"

    - name: Demo - code standards (success)
      uses: ./.github/actions/demo-code-standards
      with:
        directory: "./src/demo/coding-standards-success"

    - name: Demo - dotnet actions
      uses: ./.github/actions/demo-dotnet-actions

    - name: Demo - generate-version
      uses: ./.github/actions/demo-generate-version
      with:
        infix: "demo"

    - name: Demo - get-changed-files
      uses: ./.github/actions/demo-get-changed-files

    - name: Demo - nuget publish
      uses: ./.github/actions/demo-nuget-publish
      with:
        additional-build-args: --property WarningLevel=0 /p:VersionSuffix=1.0.0
        additional-pack-args: /p:VersionSuffix=1.0.0 /p:PackageVersion=1.0.0
        directory: "src/demo/dotnet/src/Api"
        github-token: ${{ inputs.github-token }}

    - name: Demo - get-project-and-solution-files-from-directory
      uses: ./.github/actions/demo-get-project-and-solution-files-from-directory

    - name: Demo - get-unique-root-directories
      uses: ./.github/actions/demo-get-unique-root-directories

    - name: Demo - string-manipulator
      uses: ./.github/actions/demo-string-manipulator

    - name: Demo - docker-clean-up
      uses: ./.github/actions/demo-docker-clean-up
