name: Run Demo Workflows (composite)
description: Executes all demo composite actions used by demo-all workflow

inputs:
  github-token:
    description: "GitHub token with permissions to publish to GitHub Packages (NuGet)."
    required: false
    default: ""

runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Demo - code standards (fail)
      uses: ./.github/actions/demo-code-standards
      with:
        directory: "./demo/coding-standards-fail"

    - name: Demo - code standards (fail, roslyn version)
      uses: ./.github/actions/demo-code-standards
      with:
        directory: "./demo/coding-standards-fail"
        roslyn-version: "4.9.2"

    - name: Demo - code standards (success)
      uses: ./.github/actions/demo-code-standards
      with:
        directory: "./demo/coding-standards-success"

    - name: Demo - dotnet actions
      uses: ./.github/actions/demo-dotnet-actions

    - name: Demo - generate-version
      uses: ./.github/actions/demo-generate-version
      with:
        infix: "demo"

    - name: Demo - nuget publish
      uses: ./.github/actions/demo-nuget-publish
      with:
        additional-build-args: --property WarningLevel=0 /p:VersionSuffix=1.0.0
        additional-pack-args: /p:VersionSuffix=1.0.0 /p:PackageVersion=1.0.0
        directory: "demo/dotnet/src/Api"
        github-token: ${{ inputs.github-token }}

    - name: Demo - get-match
      uses: ./.github/actions/demo-get-match

    - name: Demo - get-changed-files
      uses: ./.github/actions/demo-get-changed-files

    - name: Demo - get-project-and-solution-files-from-directory
      uses: ./.github/actions/demo-get-project-and-solution-files-from-directory

    - name: Demo - get-unique-root-directories
      uses: ./.github/actions/demo-get-unique-root-directories

    - name: Demo - string-manipulator
      uses: ./.github/actions/demo-string-manipulator
