name: "Get Unique Project Directories"
description: "Returns the unique parent project directories for each input path based on a specified file pattern (e.g. .*.cs). If no parent project is found, an empty string is returned for that path. Optionally applies a fallback regex to extract a project name from the path when no parent project file is found, which can be useful for non-standard project structures."
author: "Trafera"
inputs:
  debug-mode:
    description: "Enable debug mode for additional logging."
    required: false
    default: "false"
  fallback-regex:
    description: "Optional regex applied when no .csproj is found; if it matches, the first capture group (or full match) is used before directory flattening."
    required: false
    default: ""
  output-is-json:
    description: 'When true, outputs parent projects as a JSON array string (e.g. ["path/to/parent/project/file"]). Otherwise, outputs a comma-separated string.'
    required: false
    default: "true"
  pattern:
    description: "Regular expression used to decide which file paths should be considered when searching for parent .csproj files."
    required: true
  paths:
    description: "Comma-separated list of paths to evaluate."
    required: true

outputs:
  parent_projects:
    description: "Resolved parent project directories for each input path.  Matched output paths are guaranteed to be unique and have a .csproj file within them."
    value: ${{ steps.find-parent.outputs.parent_projects }}

runs:
  using: "composite"
  steps:
    - name: Setup Node.js
      uses: Now-Micro/actions/setup-node@v1

    - name: Find parent projects
      id: find-parent
      shell: bash
      run: node "$GITHUB_ACTION_PATH/get-unique-project-directories.js"
      env:
        INPUT_DEBUG_MODE: ${{ inputs.debug-mode }}
        INPUT_OUTPUT_IS_JSON: ${{ inputs.output-is-json }}
        INPUT_FALLBACK_REGEX: ${{ inputs.fallback-regex }}
        INPUT_PATHS: ${{ inputs.paths }}
        INPUT_PATTERN: ${{ inputs.pattern }}
