name: "Get Unique Project Directories"
description: "Returns the unique parent project directories for the input paths based on a specified file pattern (e.g. .*.cs). Paths without a matching parent project file are omitted from the result. Optionally applies a fallback regex to extract a project name from the path when no parent project file is found, which can be useful for non-standard project structures."
author: "Trafera"
inputs:
  debug-mode:
    description: "Enable debug mode for additional logging."
    required: false
    default: "false"
  fallback-regex:
    description: "Optional regex applied when no .csproj is found; if it matches, the first capture group (or full match) is used before directory flattening."
    required: false
    default: ""
  output-is-json:
    description: 'When true, outputs parent projects as a JSON array string (e.g. ["path/to/parent/project/file"]). Otherwise, outputs a comma-separated string.'
    required: false
    default: "true"
  pattern:
    description: "Regular expression used to decide which file paths should be considered when searching for parent .csproj files."
    required: true
  paths:
    description: "Comma-separated list of paths to evaluate."
    required: true
  transformer:
    description: "Optional output transformer. Supports either sed-style replacement (e.g. s#^src/#tests/#) or a regex extractor (first capture group, or full match). Applied to each resolved output path."
    required: false
    default: ""
  use-original-if-missing:
    description: "When true and transformer is provided, checks whether each transformed directory exists. If it does not exist, the original non-transformed directory is used instead. This behavior takes precedence over throw-if-transformed-not-found."
    required: false
    default: "false"
  throw-if-transformed-not-found:
    description: "When true and transformer is provided, the action exits with an error if a transformed directory does not exist. Ignored when use-original-if-missing is true."
    required: false
    default: "true"

outputs:
  unique_project_directories:
    description: "Resolved parent project directories for each input path. Matched output paths are guaranteed to be unique. When matches come from actual project files, the directories will contain a .csproj; when derived via fallback-regex, they may instead reflect a regex-based project name without a corresponding .csproj."
    value: ${{ steps.find-unique-project-directories.outputs.unique_project_directories }}

runs:
  using: "composite"
  steps:
    - name: Setup Node.js
      uses: Now-Micro/actions/setup-node@v1

    - name: Find Unique Project Directories
      id: find-unique-project-directories
      shell: bash
      run: node "$GITHUB_ACTION_PATH/get-unique-project-directories.js"
      env:
        INPUT_DEBUG_MODE: ${{ inputs.debug-mode }}
        INPUT_OUTPUT_IS_JSON: ${{ inputs.output-is-json }}
        INPUT_FALLBACK_REGEX: ${{ inputs.fallback-regex }}
        INPUT_PATHS: ${{ inputs.paths }}
        INPUT_PATTERN: ${{ inputs.pattern }}
        INPUT_TRANSFORMER: ${{ inputs.transformer }}
        INPUT_USE_ORIGINAL_IF_MISSING: ${{ inputs.use-original-if-missing }}
        INPUT_THROW_IF_TRANSFORMED_NOT_FOUND: ${{ inputs.throw-if-transformed-not-found }}
