name: Output Demo Title
description: Prints a standardized banner for demo sections

author: Trafera

inputs:
  title:
    description: "Human-readable section title"
    required: true
  path:
    description: "Path of the composite being run (for reference)"
    required: true

runs:
  using: composite
  steps:
    - name: Print title
      shell: bash
      run: |
        echo ""
        echo "========================================"
        echo "${{ inputs.title }}"
        echo "Demo: ${{ inputs.path }}"
        echo "========================================"
        echo ""
