name: Demo - Dotnet Actions (build, test, and lint)
description: This workflow demonstrates the use of various dotnet actions for building, testing, and linting a .NET project.

inputs:
  run-build-step:
    description: "Run the build step (true/false)"
    required: false
    default: "true"
  run-lint-step:
    description: "Run the lint step (true/false)"
    required: false
    default: "true"
  run-test-step:
    description: "Run the test step (true/false)"
    required: false
    default: "true"

runs:
  using: composite
  steps:
    - name: Title - Dotnet Actions Demo
      uses: ./.github/actions/output-demo-title
      with:
        title: Dotnet Actions Demo
        path: ./.github/actions/demo-dotnet-actions
    - name: Build Solution
      if: ${{ inputs.run-build-step == 'true' }}
      uses: ./dotnet/build
      with:
        file-to-build: src/demo/dotnet/demo.sln
        build-configuration: "Release"
        dotnet-version: "8.0.x"
        node-version: "18.x"

    - name: Build Project
      if: ${{ inputs.run-build-step == 'true' }}
      uses: ./dotnet/build
      with:
        file-to-build: src/demo/dotnet/src/Api/Api.csproj
        build-configuration: "Release"
        dotnet-version: "8.0.x"
        node-version: "18.x"

    - name: Run tests
      if: ${{ inputs.run-test-step == 'true' }}
      uses: ./dotnet/test
      with:
        directory: src/demo/dotnet
        dotnet-version: "8.0.x"
        project-regex: '.*Tests\.csproj\s*$'

    - name: Run tests (specific project)
      if: ${{ inputs.run-test-step == 'true' }}
      uses: ./dotnet/test
      with:
        dotnet-version: "8.0.x"
        project-file: src/demo/dotnet/tests/Api.Tests/Api.Tests.csproj

    - name: Run tests (Should Fail)
      id: test-fail
      if: ${{ inputs.run-test-step == 'true' }}
      continue-on-error: true
      uses: ./dotnet/test
      with:
        dotnet-version: "8.0.x"

    - name: Assert Failure of Previous
      if: ${{ inputs.run-test-step == 'true' }} && ${{ steps.test-fail.outcome != 'failure' }}
      shell: bash
      run: |
        echo "Expected previous test step to fail, but it did not." >&2
        exit 1

    - name: Lint
      if: ${{ inputs.run-lint-step == 'true' }}
      uses: ./dotnet/lint
