name: "Run .NET Tests (dotnet-test)"
description: "Installs one or more .NET SDKs using actions/setup-dotnet."
author: "Now-Micro"
inputs:
  dotnet-install-directory:
    description: 'Directory where .NET SDKs are installed.'
    required: false
    default: ""
  dotnet-version:
    description: 'Comma-separated list of .NET SDK versions or channels (e.g. "6.0.x,7.0.100")'
    required: true
    default: "6.0.x"

runs:
  using: "composite"
  steps:
    - name: Setup Node.js
      uses: Now-Micro/actions/setup-node@v1

    - name: Set .NET install directory
      shell: bash
      env:
        DOTNET_INSTALL_DIRECTORY: ${{ inputs['dotnet-install-directory'] != '' && inputs['dotnet-install-directory'] || format('{0}/.dotnet', runner.temp) }}
      run: |
        echo "DOTNET_INSTALL_DIR=$DOTNET_INSTALL_DIRECTORY" >> "$GITHUB_ENV"

    - name: Parse SDK versions
      id: parse_versions
      shell: bash
      run: node "$GITHUB_ACTION_PATH/dotnet-install.js"
      env:
        INPUT_DOTNET_VERSION: ${{ inputs.dotnet-version }}

    - name: Install SDK 1
      if: ${{ fromJSON(steps.parse_versions.outputs.version_count) >= 1 }}
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: ${{ steps.parse_versions.outputs.version_1 }}

    - name: Install SDK 2
      if: ${{ fromJSON(steps.parse_versions.outputs.version_count) >= 2 }}
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: ${{ steps.parse_versions.outputs.version_2 }}

    - name: Install SDK 3
      if: ${{ fromJSON(steps.parse_versions.outputs.version_count) >= 3 }}
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: ${{ steps.parse_versions.outputs.version_3 }}

    - name: Install SDK 4
      if: ${{ fromJSON(steps.parse_versions.outputs.version_count) >= 4 }}
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: ${{ steps.parse_versions.outputs.version_4 }}

    - name: Install SDK 5
      if: ${{ fromJSON(steps.parse_versions.outputs.version_count) >= 5 }}
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: ${{ steps.parse_versions.outputs.version_5 }}
