name: 'Coding Standards'
description: 'Ensure coding standards are met using analyzers'
author: 'Trafera'

inputs:
  directory:
    description: 'Directory to run coding standards checks in.  This should be the root directory of your .NET solution.'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Setup Node.js
      if: inputs.node-project-path != ''
      uses: Now-Micro/actions/setup-node@v1
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
    
    - name: Copy Relevant Files
      shell: bash
      run: |
        cp "./demo/coding-standards/.editorconfig" .
        cp -R "./demo/coding-standards/analyzers/Demo.Analyzers" ./Demo.Analyzers
        ls ./demo/coding-standards -la

    # Todo: move this into Nodejs?
    # - name: Add ItemGroup to Solution
    #   shell: bash
    #   run: dotnet sln add ./Demo.Analyzers/Demo.Analyzers.csproj

    - name: Build Solution
      shell: bash
      run: dotnet build ${{ inputs.directory }} --no-restore
