name: Setup Node.js Environment
description: Composite action to set up Node.js with caching for GitHub Actions workflows.
inputs:
  cache:
    description: 'Enable dependency caching (true/false)'
    required: false
    default: 'false'
  install-dependencies:
    description: 'Install dependencies using npm ci (true/false)'
    required: false
    default: 'false'
  node-version:
    description: 'The Node.js version to use'
    required: false
    default: '20.x'
  show-version:
    description: 'Show Node.js and npm version (true/false)'
    required: false
    default: 'false'
  
runs:
  using: "composite"
  steps:
    - name: Set up Node.js ${{ inputs.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: ${{ inputs.cache == 'true' && 'npm' || '' }}

    - name: Install dependencies
      if: ${{ inputs.install-dependencies == 'true' }}
      shell: bash
      run: npm ci

    - name: Show Node.js and npm version
      shell: bash
      if: ${{ inputs.show-version == 'true' }}
      run: |
        node --version
        npm --version