name: Demo - Validate NuGet Release
description: Demonstrates the nuget/release/validation action
author: Trafera

inputs:
  package:
    description: "Library/package name to use for workflow_dispatch scenario."
    required: false
    default: "Demo.Library"
  ref-name:
    description: "Git ref name to use for branch scenario."
    required: false
    default: "release/Demo.Library/1.2.3"
  version:
    description: "Semantic version to use for workflow_dispatch scenario."
    required: false
    default: "1.2.3"

runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Nuget Release Validation Demo
      uses: ./.github/actions/output-demo-title
      with:
        title: Nuget Release Validation Demo
        path: ./.github/actions/demo-validate-release
    - name: Run dispatch scenario
      id: dispatch
      uses: ../../nuget/release/validation
      with:
        package: ${{ inputs.package }}
        version: ${{ inputs.version }}
        debug-mode: "true"

    - name: Assert dispatch outputs
      uses: ../../src/testing/assert
      with:
        actual: ${{ steps.dispatch.outputs.library_name }}
        expected: ${{ inputs.package }}
        summary: "Dispatch library name matches"

    - name: Assert dispatch version
      uses: ../../src/testing/assert
      with:
        actual: ${{ steps.dispatch.outputs.version }}
        expected: ${{ inputs.version }}
        summary: "Dispatch version matches"

    - name: Run branch scenario
      id: branch
      uses: ../../nuget/release/validation
      with:
        ref-name: ${{ inputs.ref-name }}
        debug-mode: "true"

    - name: Assert branch library
      uses: ../../src/testing/assert
      with:
        actual: ${{ steps.branch.outputs.library_name }}
        expected: ${{ inputs.ref-name && fromJson(format('["{0}"]', inputs.ref-name))[0].split('/')[1] || '' }}
        summary: "Branch library matches ref"

    - name: Assert branch version
      uses: ../../src/testing/assert
      with:
        actual: ${{ steps.branch.outputs.version }}
        expected: ${{ inputs.ref-name && fromJson(format('["{0}"]', inputs.ref-name))[0].split('/')[2] || '' }}
        summary: "Branch version matches ref"
