name: Demo - Validate NuGet Release
description: Demonstrates the nuget/release/validation action
author: Trafera

inputs:
  package:
    description: "Library/package name to use for workflow_dispatch scenario."
    required: false
    default: "Demo.Library"
  ref-name:
    description: "Git ref name to use for branch scenario."
    required: false
    default: "release/Demo.Library/1.2.3"
  version:
    description: "Semantic version to use for workflow_dispatch scenario."
    required: false
    default: "1.2.3"

runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Initialize summary file
      shell: bash
      run: |
        echo "SUMMARY_FILE=$GITHUB_WORKSPACE/demo-validate-release-summary.txt" >> "$GITHUB_ENV"
        : > "$GITHUB_WORKSPACE/demo-validate-release-summary.txt"

    - name: Title - Nuget Release Validation Demo
      uses: ./.github/actions/output-demo-title
      with:
        title: Nuget Release Validation Demo
        path: ./.github/actions/demo-validate-release

    - name: Run dispatch scenario
      id: dispatch
      if: inputs.package != '' && inputs.version != ''
      uses: ./nuget/release/validation
      with:
        package: ${{ inputs.package }}
        version: ${{ inputs.version }}
        debug-mode: "true"

    - name: Assert dispatch outputs
      uses: ./src/testing/assert
      if: inputs.package != '' && inputs.version != ''
      with:
        actual: ${{ steps.dispatch.outputs.library_name }}
        expected: ${{ inputs.package }}
        test-name: "Dispatch library name matches"
        summary-file: ${{ env.SUMMARY_FILE }}
        summary: "Dispatch library name matches"

    - name: Assert dispatch version
      uses: ./src/testing/assert
      if: inputs.package != '' && inputs.version != ''
      with:
        actual: ${{ steps.dispatch.outputs.version }}
        expected: ${{ inputs.version }}
        test-name: "Dispatch version matches"
        summary-file: ${{ env.SUMMARY_FILE }}
        summary: "Dispatch version matches"

    - name: Run branch scenario (expected failure)
      if: inputs.ref-name != '' && !startsWith(inputs.ref-name, 'release/')
      id: branch_fail
      continue-on-error: true
      shell: bash
      run: |
        out_file="$RUNNER_TEMP/branch-fail-out.txt"
        export GITHUB_OUTPUT="$out_file"
        set +e
        output=$(INPUT_REF_NAME="${{ inputs.ref-name }}" node ./nuget/release/validation/validation.js 2>&1)
        status=$?
        printf 'log<<EOF\n%s\nEOF\n' "$output" >> "$GITHUB_OUTPUT"
        echo "status=$status" >> "$GITHUB_OUTPUT"
        exit 0

    - name: Assert branch failure status
      if: inputs.ref-name != '' && !startsWith(inputs.ref-name, 'release/')
      uses: ./src/testing/assert
      with:
        actual: ${{ steps.branch_fail.outputs.status }}
        expected: 1
        test-name: "Branch non-release exits 1"
        summary-file: ${{ env.SUMMARY_FILE }}

    - name: Assert branch failure message
      if: inputs.ref-name != '' && !startsWith(inputs.ref-name, 'release/')
      uses: ./src/testing/assert
      with:
        actual: ${{ steps.branch_fail.outputs.log }}
        expected: INPUT_PACKAGE is required when ref does not match release/*
        mode: present
        test-name: "Branch non-release failure message"
        summary-file: ${{ env.SUMMARY_FILE }}
