name: Demo - Validate NuGet Release
description: Demonstrates the nuget/release/validation action
author: Trafera

inputs:
  package:
    description: "Library/package name to use for workflow_dispatch scenario."
    required: false
    default: "Demo.Library"
  ref-name:
    description: "Git ref name to use for branch scenario."
    required: false
    default: "release/Demo.Library/1.2.3"
  version:
    description: "Semantic version to use for workflow_dispatch scenario."
    required: false
    default: "1.2.3"

runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Run dispatch scenario
      id: dispatch
      uses: ../../nuget/release/validation
      with:
        package: ${{ inputs.package }}
        version: ${{ inputs.version }}
        debug-mode: "true"

    - name: Assert dispatch outputs
      shell: bash
      run: |
        test "${{ steps.dispatch.outputs.library_name }}" = "${{ inputs.package }}"
        test "${{ steps.dispatch.outputs.version }}" = "${{ inputs.version }}"
        echo "Dispatch scenario outputs validated"

    - name: Run branch scenario
      id: branch
      uses: ../../nuget/release/validation
      with:
        ref-name: ${{ inputs.ref-name }}
        debug-mode: "true"

    - name: Assert branch outputs
      shell: bash
      run: |
        pkg="$(echo "${{ inputs.ref-name }}" | cut -d'/' -f2)"
        ver="$(echo "${{ inputs.ref-name }}" | cut -d'/' -f3)"
        test "${{ steps.branch.outputs.library_name }}" = "$pkg"
        test "${{ steps.branch.outputs.version }}" = "$ver"
        echo "Branch scenario outputs validated"
