name: Demo - Generate HTTPS Certificate
description: Demonstrates the generate-https-cert action
author: Trafera

runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Title - Generate Https Cert Demo
      uses: ./.github/actions/output-demo-title
      with:
        title: Generate Https Cert Demo
        path: ./.github/actions/demo-generate-https-cert

    - name: Generate HTTPS certificate
      uses: ./generate-https-cert
      with:
        debug-mode: "true"
        cert-password: "abc1234!"
        force-new-cert: "true"

    - name: Assert certificate location
      shell: bash
      run: |
        test -f ${{ env.CERT_PATH }} || (ls $(dirname ${{ env.CERT_PATH }}) && false)

    - name: Prepare alternate workspace
      shell: bash
      run: |
        mkdir -p ${{ env.WORKING_DIR }}

    - name: Generate HTTPS certificate in alternate workspace
      uses: ./generate-https-cert
      with:
        debug-mode: "true"
        cert-path: ${{ env.CERT_PATH }}
        cert-password: "abc1234!"
        working-directory: ${{ env.WORKING_DIR }}
        force-new-cert: "true"

    - name: Assert alternate path
      shell: bash
      run: |
        test -f ${{ env.WORKING_DIR }}/${{ env.CERT_PATH }}
        echo "Alternate certificate created at ${{ env.WORKING_DIR }}/${{ env.CERT_PATH }}"

    - name: Generate HTTPS certificate in alternate workspace (using absolute path)
      uses: ./generate-https-cert
      with:
        debug-mode: "true"
        cert-path: ${{ env.CERT_PATH }}
        cert-password: "abc1234!"
        working-directory: ${{ env.ABSOLUTE_DIR }}
        force-new-cert: "true"

    - name: Assert alternate path
      shell: bash
      run: |
        test -f ${{ env.ABSOLUTE_DIR }}/${{ env.CERT_PATH }}
        echo "Alternate certificate created at ${{ env.ABSOLUTE_DIR }}/${{ env.CERT_PATH }}"

