name: 'Run dotnet lint checks'
description: 'Runs checks for a specific directory'
author: 'Trafera'

inputs:
  csharpierrc-path:
    description: 'Path to the csharpierrc.yaml file'
    required: false
    default: './.config/csharpierrc.yaml'
  csharpier-version:
    description: 'Version of CSharpier to use'
    required: false
    default: '1.1.2'
  tools-json-path:
    description: 'Path to the dotnet-tools.json file'
    required: false
    default: './.config/dotnet-tools.json'

runs:
  using: 'composite'
  steps:
    - name: Setup Node.js
      uses: Now-Micro/actions/setup-node@v1

    - name: Ensure files are present
      shell: bash
      run: node "$GITHUB_ACTION_PATH/ensure-files.js"
      env:
        INPUT_CSHARPIERRC_PATH: ${{ inputs.csharpierrc-path }}
        INPUT_CSHARPIER_VERSION: ${{ inputs.csharpier-version }}
        INPUT_TOOLS_JSON_PATH: ${{ inputs.tools-json-path }}

    - name: Ensure csharpier tool entry present
      shell: bash
      run: node "$GITHUB_ACTION_PATH/ensure-csharpier-tool.js"
      env:
        INPUT_CSHARPIER_VERSION: ${{ inputs.csharpier-version }}
        INPUT_TOOLS_JSON_PATH: ${{ inputs.tools-json-path }}

    - name: Print Working Directory
      shell: bash
      run: pwd
      
    - name: Run lint checks
      shell: bash
      run: |
          dotnet tool restore
          dotnet csharpier check .
