name: 'Run dotnet lint checks'
description: 'Runs checks for a specific directory'
author: 'Trafera'

inputs:
  tools-json-path:
    description: 'Path to the dotnet-tools.json file'
    required: false
    default: './.config/dotnet-tools.json'
  csharpierrc-path:
    description: 'Path to the csharpierrc.yaml file'
    required: false
    default: './.config/csharpierrc.yaml'

runs:
  using: 'composite'
  steps:
    - name: Ensure files are present
      shell: bash
      run: |
        if [ ! -f "${{ inputs.csharpierrc-path }}" ]; then
          echo "${{ inputs.csharpierrc-path }} file is missing.  Using default settings."
          # copy over the one from this folder
          cp "$GITHUB_ACTION_PATH/.config/csharpierrc.yaml" "${{ inputs.csharpierrc-path }}"
        fi
        if [ ! -f "${{ inputs.tools-json-path }}" ]; then
          echo "${{ inputs.tools-json-path }} file is missing.  Using default version."
          # copy over the one from this folder
          cp "$GITHUB_ACTION_PATH/${{ inputs.tools-json-path }}" "${{ inputs.tools-json-path }}"
        fi

    - name: Ensure Tools.Csharpier section is present
      shell: bash
      run: |
        cat "${{ inputs.tools-json-path }}"

    - name: Print Working Directory
      shell: bash
      run: pwd

    - name: Run lint checks
      shell: bash
      run: |
          dotnet tool restore
          dotnet csharpier check .
  