name: 'Run dotnet lint checks'
description: 'Runs checks for a specific directory'
author: 'Trafera'

inputs:
  csharpierrc-path:
    description: 'Path to the csharpierrc.yaml file'
    required: false
    default: './.config/csharpierrc.yaml'
  csharpier-version:
    description: 'Version of csharpier to ensure in dotnet-tools.json'
    required: false
    default: '1.1.2'
  directory:
    description: 'Directory to run csharpier against'
    required: false
    default: '.'
  dotnet-version:
    description: 'Optional dotnet version to install (e.g. 8.0.x)'
    required: false
    default: '8.0.x'
  tools-json-path:
    description: 'Path to the dotnet-tools.json file'
    required: false
    default: './.config/dotnet-tools.json'

runs:
  using: 'composite'
  steps:
    - name: Ensure files are present
      shell: bash
      run: |
        set -euo pipefail
        CSHARPIER_CFG='${{ inputs.csharpierrc-path }}'
        TOOLS_JSON='${{ inputs.tools-json-path }}'
        mkdir -p "$(dirname "$CSHARPIER_CFG")"
        mkdir -p "$(dirname "$TOOLS_JSON")"
        if [ ! -f "$CSHARPIER_CFG" ]; then
          echo "$CSHARPIER_CFG file is missing. Creating default.";
          printf '%s\n' 'printWidth: 120' 'useTabs: false' 'endOfLine: lf' > "$CSHARPIER_CFG"
        else
          echo "Found existing $CSHARPIER_CFG";
        fi
        if [ ! -f "$TOOLS_JSON" ]; then
          echo "$TOOLS_JSON file is missing. Creating default.";
          printf '%s\n' '{' '  "version": 1,' '  "isRoot": true,' '  "tools": {}' '}' > "$TOOLS_JSON"
        else
          echo "Found existing $TOOLS_JSON";
        fi
        echo 'State after ensure:'
        ls -al "$(dirname "$TOOLS_JSON")"

    - name: Ensure csharpier tool entry present
      shell: bash
      run: |
        set -euo pipefail
        node -e "const fs=require('fs');const file='${{ inputs.tools-json-path }}';const ver='${{ inputs.csharpier-version }}';const d=JSON.parse(fs.readFileSync(file,'utf8'));if(!d.tools)d.tools={};if(!d.tools.csharpier){d.tools.csharpier={version:ver,commands:['csharpier']};fs.writeFileSync(file,JSON.stringify(d,null,2)+'\n');console.log('Injected csharpier tool definition '+ver);}else{console.log('csharpier tool already present '+d.tools.csharpier.version);}"
        echo '--- dotnet-tools.json ---'
        cat '${{ inputs.tools-json-path }}'

    - name: Setup .NET (optional)
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ inputs.dotnet-version }}

    - name: Print Working Directory
      shell: bash
      run: pwd

    - name: Restore tools
      shell: bash
      run: dotnet tool restore

    - name: Run lint checks
      shell: bash
      run: |
          dotnet tool restore
          dotnet csharpier check 
