name: 'Get Unique Root Directories'
description: 'Detects unique root directories from changed files and returns them as a JSON array'
author: 'Trafera'
inputs: 
  debug-mode:
    description: 'Enable debug mode for additional logging.'
    required: false
    default: 'false'
  pattern:
    description: 'Regular expression used to determine which file names should be used for generating unique root directories.'
    required: true
  paths:
    description: 'Comma-separated list of paths'
    required: true

outputs:
  unique_root_directories:
    description: 'JSON array of unique root directories'
    value: ${{ steps.parse-changes.outputs.unique_root_directories }}

runs:
  using: 'composite'
  steps:
    - name: Setup Node.js
      uses: Now-Micro/actions/setup-node@v1

    - name: Determine changed project directories
      id: parse-changes
      shell: bash
      run: node "$GITHUB_ACTION_PATH/unique-root-directories.js"
      env:
        INPUT_DEBUG_MODE: ${{ inputs.debug-mode }}
        INPUT_PATHS: ${{ inputs.paths }}
        INPUT_PATTERN: ${{ inputs.pattern }}
