name: Demo - Generate Version
description: Demonstrates the generate-version action reading csproj or releases and asserts basic shape

author: Trafera

inputs:
  infix:
    description: "Optional infix to include between version and timestamp"
    required: false
    default: "demo"
  release-keyword:
    description: "Optional keyword to search releases; empty to use project file only"
    required: false
    default: ""

runs:
  using: composite
  steps:
    - name: Prepare summary and temp project
      id: pre
      shell: bash
      run: |
        echo "summary_file=$(pwd)/gv-summary.txt" >> "$GITHUB_OUTPUT"
        # ensure summary file exists to avoid cat errors if earlier steps fail
        touch "$(pwd)/gv-summary.txt"
        mkdir -p _gv
        cat > _gv/Demo.App.csproj <<'EOF'
        <Project Sdk="Microsoft.NET.Sdk">
          <PropertyGroup>
            <TargetFramework>net8.0</TargetFramework>
            <Version>2.3.4-beta</Version>
          </PropertyGroup>
        </Project>
        EOF
        echo "project_file=$(pwd)/_gv/Demo.App.csproj" >> "$GITHUB_OUTPUT"

    - name: Run generate-version (csproj)
      id: csproj
      uses: ./generate-version
      with:
        project-file: ${{ steps.pre.outputs.project_file }}
        infix-value: ${{ inputs.infix }}

    - name: Assert version shape (csproj)
      uses: ./testing/assert
      with:
        test-name: "version from csproj has timestamp"
        summary-file: ${{ steps.pre.outputs.summary_file }}
        mode: regex
        expected: '^\d+\.\d+\.\d+-[A-Za-z0-9]+-\d{12}$'
        actual: ${{ steps.csproj.outputs['version-number'] }}

    - name: Run generate-version (releases)
      id: rel
      if: ${{ inputs['release-keyword'] != '' }}
      uses: ./generate-version
      with:
        project-file: ${{ steps.pre.outputs.project_file }}
        infix-value: ${{ inputs.infix }}
        release-keyword: ${{ inputs['release-keyword'] }}

    - name: Run generate-version (releases - initial version)
      id: rel_initial
      uses: ./generate-version
      with:
        project-file: ${{ steps.pre.outputs.project_file }}
        infix-value: ${{ inputs.infix }}
        release-keyword: "initial version"

    - name: Assert version shape (releases - initial version)
      uses: ./testing/assert
      with:
        test-name: "version from releases (initial version) has timestamp"
        summary-file: ${{ steps.pre.outputs.summary_file }}
        mode: regex
        expected: '^\d+\.\d+\.\d+-[A-Za-z0-9]+-\d{12}$'
        actual: ${{ steps.rel_initial.outputs['version-number'] }}

    - name: Assert base version is 1.0.0 (releases - initial version)
      uses: ./testing/assert
      with:
        test-name: "base version 1.0.0 for initial version keyword"
        summary-file: ${{ steps.pre.outputs.summary_file }}
        mode: regex
        expected: '^1\\.0\\.0-'
        actual: ${{ steps.rel_initial.outputs['version-number'] }}

    - name: Summarize
      if: always()
      shell: bash
      run: |
        echo '=== Generate Version Demo Summary ===' >> "$GITHUB_STEP_SUMMARY"
        if [ -f "${{ steps.pre.outputs.summary_file }}" ]; then
          cat "${{ steps.pre.outputs.summary_file }}" >> "$GITHUB_STEP_SUMMARY"
        else
          echo "(no per-step summary file present)" >> "$GITHUB_STEP_SUMMARY"
        fi
        if [ -n "${{ steps.rel_initial.outputs['version-number'] }}" ]; then
          echo "Initial version keyword output: ${{ steps.rel_initial.outputs['version-number'] }}" >> "$GITHUB_STEP_SUMMARY"
        fi
