name: Demo - NuGet Publish
description: Demo for nuget/publish composite action

inputs:
  directory:
    description: "Directory to search for project"
    required: false
    default: "demo/dotnet/src/Api"
  github-token:
    description: "GitHub token for deploying nuget packages."
    required: false
    default: ""

runs:
  using: composite
  steps:
    - name: Setup summary file
      shell: bash
      run: |
        echo "SUMMARY_FILE=$GITHUB_WORKSPACE/demo-nuget-publish-summary.txt" >> $GITHUB_ENV
        : > $GITHUB_WORKSPACE/demo-nuget-publish-summary.txt

    - name: Run nuget/publish (expected to fail push)
      id: nuget_publish
      continue-on-error: true
      uses: ./nuget/publish
      with:
        directory: ${{ inputs.directory }}
        dotnet-version: "8.0.x"
        github-token: ${{ inputs.github-token }}
        project-regex: 'Api\.csproj$'

    - name: Assert nupkg exists
      uses: ./testing/assert
      with:
        expected: present
        mode: present
        actual: ${{ (hashFiles('nupkgs/*.nupkg') != '') && 'present' || '' }}
        test-name: "nupkg was produced by pack"
        summary-file: ${{ env.SUMMARY_FILE }}

    - name: Run nuget/publish (success to local folder)
      id: nuget_publish_success
      uses: ./nuget/publish
      with:
        directory: ${{ inputs.directory }}
        dotnet-version: "8.0.x"
        github-token: ${{ inputs.github-token }}
        project-regex: 'Api\.csproj$'
        publish-source: '.artifacts/nuget-local'

    - name: List local publish folder
      shell: bash
      run: |
        mkdir -p .artifacts/nuget-local
        ls -la .artifacts/nuget-local || true

    - name: Assert locally published nupkg exists
      uses: ./testing/assert
      with:
        expected: present
        mode: present
        actual: ${{ (hashFiles('.artifacts/nuget-local/*.nupkg') != '') && 'present' || '' }}
        test-name: "local publish succeeded"
        summary-file: ${{ env.SUMMARY_FILE }}

    - name: Summary
      shell: bash
      if: always()
      run: |
        echo "### Demo nuget/publish" >> $GITHUB_STEP_SUMMARY
        echo "All Tests:" >> $GITHUB_STEP_SUMMARY
        cat "$SUMMARY_FILE" >> $GITHUB_STEP_SUMMARY
