name: Assert
description: Make assertions in GitHub Actions workflows to mimic test frameworks.
inputs:
  actual:
    description: "The actual value to compare against the expected value"
    required: true
  exit-on-fail:
    description: "Exit with code 1 if the assertion fails"
    required: false
    default: "false"
  expected:
    description: "The expected value (string or regex suffix)."
    required: true
  mode:
    description: "Comparison mode: exact | endswith | present | absent | regex"
    required: false
    default: "exact"
  summary-file:
    description: "Path to the summary file where results will be logged"
    required: true
  test-name:
    description: "Name of the test for summary output"
    required: true

runs:
  using: "composite"
  steps:
    - name: Install Node.js
      uses: ./setup-node

    - name: Run assertion
      shell: bash
      run: node ./src/testing/assert/assert.js
      env:
        INPUT_ACTUAL: ${{ inputs.actual }}
        INPUT_EXIT_ON_FAIL: ${{ inputs.exit-on-fail }}
        INPUT_EXPECTED: ${{ inputs.expected }}
        INPUT_MODE: ${{ inputs.mode }}
        INPUT_PARTIAL_MATCH_ALLOWED: ${{ inputs.partial-match-allowed }}
        INPUT_SUMMARY_FILE: ${{ inputs.summary-file }}
        INPUT_TEST_NAME: ${{ inputs.test-name }}
