name: "Generate HTTPS Certificate"
description: "Generates a self-signed HTTPS certificate for .NET deployments"
author: "Trafera"

inputs:
  cert-path:
    description: "The path to the certificate file (e.g., certs/aspnetapp.pfx)."
    required: false
    default: "certs/aspnetapp.pfx"
  cert-password:
    description: "Password used when exporting the certificate. Prefer passing a secret."
    required: true
    default: ""
  debug-mode:
    description: "Enable verbose debugging output (true|false)."
    required: false
    default: "false"
  force-new-cert:
    description: "Force clearing the dev cert store before exporting a new cert (true|false)."
    required: false
    default: "false"
  working-directory:
    description: "Directory to run the action in (fall back to workspace when empty)."
    required: false
    default: ""

runs:
  using: "composite"
  steps:
    - name: Setup Node.js
      uses: Now-Micro/actions/setup-node@v1

    - name: Generate HTTPS certificate
      working-directory: ${{ inputs.working-directory && format('{0}/{1}', github.workspace, inputs.working-directory) || github.workspace }}
      env:
        INPUT_CERT_PATH: ${{ inputs.cert-path }}
        INPUT_CERT_PASSWORD: ${{ inputs.cert-password || env.CERT_PASSWORD }}
        INPUT_WORKSPACE_DIR: ${{ inputs.working-directory && format('{0}/{1}', github.workspace, inputs.working-directory) || github.workspace }}
        WORKSPACE_DIR: ${{ inputs.working-directory && format('{0}/{1}', github.workspace, inputs.working-directory) || env.WORKSPACE_DIR || github.workspace }}
        INPUT_DEBUG_MODE: ${{ inputs.debug-mode || env.DEBUG_MODE || 'false' }}
        INPUT_FORCE_NEW_CERT: ${{ inputs.force-new-cert || env.FORCE_NEW_CERT || 'false' }}
      run: |
        node "$GITHUB_ACTION_PATH/generate-https-cert.js"
      shell: bash
