name: "Validate NuGet release configuration"
description: "Parses release inputs or branch names to extract library name and semantic version."
author: "Trafera"

inputs:
  package:
    description: "Library/package name (required for workflow_dispatch)."
    required: false
    default: ""
  version:
    description: "Semantic version (X.Y.Z or prerelease). Required for workflow_dispatch."
    required: false
    default: ""
  event-name:
    description: "GitHub event name (workflow_dispatch, push, etc.). Defaults to github.event_name."
    required: false
    default: ""
  ref-name:
    description: "Git ref name (e.g., release/Package/1.2.3). Defaults to github.ref_name."
    required: false
    default: ""
  debug-mode:
    description: "Enable verbose debug logging."
    required: false
    default: "false"

outputs:
  version:
    description: "Parsed semantic version"
    value: ${{ steps.validate.outputs.version }}
  library_name:
    description: "Parsed library/package name"
    value: ${{ steps.validate.outputs.library_name }}

runs:
  using: "composite"
  steps:
    - name: Setup Node.js
      uses: Now-Micro/actions/setup-node@v1

    - name: Validate release configuration
      id: validate
      env:
        INPUT_PACKAGE: ${{ inputs.package }}
        INPUT_VERSION: ${{ inputs.version }}
        INPUT_EVENT_NAME: ${{ inputs.event-name || github.event_name }}
        INPUT_REF_NAME: ${{ inputs.ref-name || github.ref_name }}
        INPUT_DEBUG_MODE: ${{ inputs.debug-mode || 'false' }}
      run: |
        node "$GITHUB_ACTION_PATH/validation.js"
      shell: bash
