name: Get Last Workflow Success SHA
description: Finds the SHA of the last successful workflow run on the current branch by checking job conclusions
inputs:
  branch:
    description: Branch name to search for workflow runs
    required: false
    default: ${{ github.head_ref }}
  debug-mode:
    description: Enable debug logging
    required: false
    default: "false"
  default-branch:
    description: Default branch name to use as fallback
    required: false
    default: ${{ github.event.repository.default_branch }}
  github-token:
    description: GitHub token for API access
    required: false
    default: ${{ github.token }}
  main-job-name:
    description: The name of the main job that must have succeeded. A job's name is defined in the workflow file in one of two places.  Either the job key itself (e.g., "test-setup") or the `name` property within the job definition.
    required: true
  request-size:
    description: Number of workflow runs to fetch per API request
    required: false
    default: "50"
  retry-attempts:
    description: Maximum number of retry attempts for API requests
    required: false
    default: "3"
  job-names-that-must-succeed:
    description: Comma-separated list of job names that must have passed or been skipped. A job's name is defined in the workflow file in one of two places.  Either the job key itself (e.g., "test-setup") or the `name` property within the job definition.
    required: true
  workflow-name:
    description: The workflow filename to check (e.g., "checks.yml")
    required: true

outputs:
  last_success_sha:
    description: The SHA of the last successful workflow run, or the default branch name if none found
    value: ${{ steps.find-sha.outputs.last_success_sha }}

runs:
  using: composite
  steps:
    - name: Find last successful workflow run SHA
      id: find-sha
      shell: bash
      env:
        GITHUB_REPOSITORY: ${{ github.repository }}
        INPUT_BRANCH: ${{ inputs.branch }}
        INPUT_DEBUG_MODE: ${{ inputs.debug-mode }}
        INPUT_DEFAULT_BRANCH: ${{ inputs.default-branch }}
        INPUT_GITHUB_TOKEN: ${{ inputs.github-token }}
        INPUT_JOB_NAMES_THAT_MUST_SUCCEED: ${{ inputs.job-names-that-must-succeed }}
        INPUT_MAIN_JOB_NAME: ${{ inputs.main-job-name }}
        INPUT_REQUEST_SIZE: ${{ inputs.request-size }}
        INPUT_RETRY_ATTEMPTS: ${{ inputs.retry-attempts }}
        INPUT_WORKFLOW_NAME: ${{ inputs.workflow-name }}
      run: node "$GITHUB_ACTION_PATH/get-last-workflow-success-sha.js"
