name: Demo - All
on:
  workflow_dispatch:

jobs:
  run-demos:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Run all demo composites
        uses: ./.github/actions/run-demo-workflows

