name: Demo - get-match
on:
  workflow_dispatch:

jobs:
  demo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run demo
        uses: ./.github/actions/demo-get-match
