name: Demo - Get Unique Root Directories
on:
  workflow_dispatch: {}

jobs:
  demo-get-unique-root-directories:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Run demo for get-unique-root-directories
        uses: ./.github/actions/demo-get-unique-root-directories
      
