name: Demo - Dotnet Actions (build, test, and lint)
on:
  workflow_dispatch:

jobs:
  demo-dotnet:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Build
        uses: ./dotnet/build
        with:   
            solution-file: demo/dotnet/demo.sln
            build-configuration: 'Release'
            dotnet-version: '8.0.x'
            node-version: '18.x'

      - name: Run tests
        uses: ./dotnet/test
        with:
            directory: demo/dotnet
        
      - name: Lint
        uses: ./dotnet/lint
        with:
            directory: demo/dotnet

