name: Demo - npm Publish

on:
    workflow_dispatch:
        inputs:
            delete-published-package:
                description: "When true, deletes the published demo package version after the run."
                required: false
                type: boolean
                default: true
            node-version:
                description: "Node.js version to use."
                required: false
                type: string
                default: "22.x"

jobs:
    demo-npm-publish:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
              with:
                  fetch-depth: 0

            - name: Run npm publish demo
              uses: ./.github/actions/demo-npm-publish
              with:
                  delete-published-package: ${{ inputs['delete-published-package'] }}
                  github-token: ${{ secrets.GITHUB_TOKEN }}
                  token-github-packages: ${{ secrets.TOKEN_GITHUB_PACKAGES }}
