name: Demo - Validate NuGet Release - Release Branch

on:
    workflow_dispatch:

jobs:
    demo:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout 
              uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

            - name: Run demo
              uses: ./.github/actions/demo-validate-release
              with:
                  skip-ref-scenario: "false"
                  ref-name: ${{ github.ref_name }}

