name: Demo - Get Unique Root Directories
on:
  workflow_dispatch: {}

jobs:
  demo-get-unique-root-directories:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Run demo for get-unique-root-directories
        uses: ./.github/actions/demo-get-unique-root-directories
