name: Demo - Get Project and Solution Files
on:
  workflow_dispatch:

jobs:
  demo-get-project-and-solution-files:
    runs-on: ubuntu-latest
    steps:
      - name: Run demo for get-project-and-solution-files-from-directory
        uses: ./.github/actions/demo-get-project-and-solution-files-from-directory

